[build-system]
build-backend = "setuptools.build_meta"

requires = [
  "setuptools",
]

[project]
name = "phidata"
version = "2.4.18"
description = "Memory, knowledge and tools for LLMs."
readme = "README.md"
authors = [
  { name = "Ashpreet Bedi", email = "ashpreet@phidata.com" },
]

requires-python = ">=3.7"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]
dependencies = [
  "gitpython",
  "httpx",
  "pydantic",
  "pydantic-settings",
  "python-dotenv",
  "pyyaml",
  "rich",
  "tomli",
  "typer",
  "typing-extensions",
]

optional-dependencies.aws = [
  "boto3",
  "docker",
]
optional-dependencies.dev = [
  "mypy",
  "pytest",
  "ruff",
  "types-pyyaml",
]
optional-dependencies.docker = [
  "docker",
]
optional-dependencies.k8s = [
  "docker",
  "kubernetes",
]
urls.documentation = "https://docs.phidata.com"
urls.homepage = "https://phidata.com"
scripts.phi = "phi.cli.entrypoint:phi_cli"

[tool.setuptools.packages.find]
include = [
  "phi*",
]

[tool.setuptools.package-data]
phi = [
  "py.typed",
]

[tool.ruff]
line-length = 140
exclude = [
  "aienv*",
  "phienv*",
]
lint.per-file-ignores."__init__.py" = [
  "F401",
]
lint.per-file-ignores."phi/k8s/app/traefik/crds.py" = [
  "E501",
]
select = [
  'E',
  'W',
  'F',
  'I',
]
# 2. Avoid enforcing line-length violations (`E501`)
ignore = [
  "E501",
]

[tool.pytest.ini_options]
testpaths = "tests"

[tool.mypy]
check_untyped_defs = true
no_implicit_optional = true
warn_unused_configs = true
plugins = [
  "pydantic.mypy",
]
exclude = [
  "phienv*",
  "aienv*",
  "scratch*",
  "wip*",
  "tmp*",
  "cookbook/examples/*",
  "phi/assistant/openai/*",
]

[[tool.mypy.overrides]]
module = [
  "altair.*",
  "arxiv.*",
  "anthropic.*",
  "apify_client.*",
  "boto3.*",
  "botocore.*",
  "bs4.*",
  "cohere.*",
  "docker.*",
  "duckdb.*",
  "exa_py.*",
  "firecrawl.*",
  "duckduckgo_search.*",
  "groq.*",
  "kubernetes.*",
  "lancedb.*",
  "langchain.*",
  "langchain_core.*",
  "llama_index.*",
  "mistralai.*",
  "newspaper.*",
  "nest_asyncio.*",
  "numpy.*",
  "ollama.*",
  "openai.*",
  "openbb.*",
  "pandas.*",
  "pinecone.*",
  "pyarrow.*",
  "pgvector.*",
  "psycopg.*",
  "psycopg2.*",
  "pypdf.*",
  "qdrant_client.*",
  "rapidocr_onnxruntime.*",
  "requests.*",
  "simplejson.*",
  "serpapi.*",
  "setuptools.*",
  "sqlalchemy.*",
  "streamlit.*",
  "tavily.*",
  "textract.*",
  "vertexai.*",
  "voyageai.*",
  "wikipedia.*",
  "yfinance.*",
  "youtube_transcript_api.*",
]
ignore_missing_imports = true
